# Use the official Nginx image as a base
FROM nginx:alpine

# Remove the default nginx.conf

# Copy custom nginx.conf


# Copy the index.html from Express public directory to Nginx
COPY ../express/public /usr/share/nginx/html/

# Expose port 8080
EXPOSE 8080